# ================================
# ğŸš€ Device Configuration
# ================================
device: "cuda"  # "cuda" náº¿u cÃ³ GPU, "cpu" náº¿u khÃ´ng

# ================================
# ğŸ·ï¸ Training Hyperparameters
# ================================
batch_size: 32
num_epochs: 10
learning_rate: 0.0001
weight_decay: 0.0005
momentum: 0.9

# ================================
# ğŸ“‚ Dataset Paths
# ================================
dataset_path: "datasets/archive/Market-1501-v15.09.15/bounding_box_train"
checkpoint_dir: "./checkpoints"
log_dir: "./logs"

# ================================
# ğŸ¯ Model Parameters
# ================================
input_size: [224, 224]  # Chiá»u cao, chiá»u rá»™ng
backbone: "resnet50"    # CÃ¡c lá»±a chá»n: resnet50 / facenet / efficientnet
pretrained: true

# ================================
# ğŸŒ± Reproducibility
# ================================
seed: 42


output_url: "/output_video"
# url = "rtsp://admin:Tinvl12345@@192.168.1.13:554/media/live/1/main"
url: 0
# url = "rtsp://admin:Tinvl12345@@192.168.0.149:554/media/live/1/main"
# url = "rtsp://admin:Tinvl1903@@192.168.0.103:554/media/live/1/main"
# url = "rtsp://admin:Tinvl1903@@169.254.17.253:554/media/live/1/main"
# url = r"D:\Dissertation\Re-id\sample video\footage_2.mp4"  # Use video file path or 0 for webcam